apiVersion: v2
name: finance
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
maintainers:
  - name: Ismael Alves
    email: cearaismael1997@gmail.com
    url: 'https://github.com/ismaelalvesgit'