{{- range .Values.jobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $.Release.Name }}-{{ .name }}-job"
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{ else if or $.Values.namespace $.Release.Namespace }}
  namespace: {{ or $.Values.namespace $.Release.Namespace }}
  {{- end }}
  labels:
    {{- if .labels.jobgroup }}
    jobgroup: {{ .labels.jobgroup }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
  annotations:
    meta.helm.sh/release-name: {{ $.Chart.Name }}
spec:
  schedule: {{ .schedule | quote }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      parallelism: 1
      backoffLimit: 4
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: "{{ .name }}-job"
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
              imagePullPolicy: Always
              env:
                {{- range $key, $value := $.Values.env }}
                {{- if $value }}
                - name: {{ $key | upper }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- end }}
                {{- range $key, $value := $.Values.secret }}
                {{- if $value }}
                - name: {{ $key | upper }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "service.fullname" $ }}
                      key: {{ $key | upper }}
                {{- end }}
                {{- end }}
              command:
                - npx
                - babel-node
                - cron
                - {{ .command }}
---
{{- end }}